# coding: utf-8

"""
    Safemat Api

    The Safemat REST API permits applications to connect securely to the Safemat software to carry out a multitude of operations.  Authentication and token-based access control is enforced.  ### Token: <table><thead><tr><th>Name</th><th>Token type</th><th>Lifetime</th></tr></thead><tbody><tr><td>Access token</td><td><a rel=\"noopener noreferrer\" target=\"_blank\" href=\"https://jwt.io/\">JWT</a>., Bearer token</td><td>60m</td></tr></tbody></table>  ### Access token usage  API requests (where authorisation is required) must include the bearer access token in the header.  Once the access token expires it should be refreshed.   ### How to determine if the token has expired <ol> <li>The API returns a 401 error.</li> <li>Check the <code>exp</code> field in the token payloads.</li> </ol>  ### Token structure  <table><thead><tr><th>Key name</th><th>Description</th></tr></thead><tbody><tr><td>exp</td><td>Expiration date and time in UNIX format</td></tr><tr><td>uid</td><td>Token owner(Unique number of devices(terminal))</td></tr><tr><td>terminal_id</td><td>Id in base of devices(terminal`s)</td></tr><tr><td>iat</td><td>Created date and time in UNIX format</td></tr></tbody></table>    # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.accounts_api import AccountsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_account(self):
        """Test case for create_account

        Create account  # noqa: E501
        """
        pass

    def test_credit_account(self):
        """Test case for credit_account

        Credit request.  # noqa: E501
        """
        pass

    def test_credit_review_account(self):
        """Test case for credit_review_account

        Evaluates credit request.  # noqa: E501
        """
        pass

    def test_debit_account(self):
        """Test case for debit_account

        Debit request.  # noqa: E501
        """
        pass

    def test_debit_review_account(self):
        """Test case for debit_review_account

        Evaluates debit request.  # noqa: E501
        """
        pass

    def test_get_account(self):
        """Test case for get_account

        Get account`s info  # noqa: E501
        """
        pass

    def test_get_list_accounts(self):
        """Test case for get_list_accounts

        Get accounts list  # noqa: E501
        """
        pass

    def test_transfer_account(self):
        """Test case for transfer_account

        Create transfer request.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
