# coding: utf-8

# flake8: noqa

"""
    Safemat Api

    The Safemat REST API permits applications to connect securely to the Safemat software to carry out a multitude of operations.  Authentication and token-based access control is enforced.  ### Token: <table><thead><tr><th>Name</th><th>Token type</th><th>Lifetime</th></tr></thead><tbody><tr><td>Access token</td><td><a rel=\"noopener noreferrer\" target=\"_blank\" href=\"https://jwt.io/\">JWT</a>., Bearer token</td><td>60m</td></tr></tbody></table>  ### Access token usage  API requests (where authorisation is required) must include the bearer access token in the header.  Once the access token expires it should be refreshed.   ### How to determine if the token has expired <ol> <li>The API returns a 401 error.</li> <li>Check the <code>exp</code> field in the token payloads.</li> </ol>  ### Token structure  <table><thead><tr><th>Key name</th><th>Description</th></tr></thead><tbody><tr><td>exp</td><td>Expiration date and time in UNIX format</td></tr><tr><td>uid</td><td>Token owner(Unique number of devices(terminal))</td></tr><tr><td>terminal_id</td><td>Id in base of devices(terminal`s)</td></tr><tr><td>iat</td><td>Created date and time in UNIX format</td></tr></tbody></table>    # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.accounts_api import AccountsApi
from swagger_client.api.auth_api import AuthApi
from swagger_client.api.sessions_api import SessionsApi
from swagger_client.api.terminals_api import TerminalsApi
from swagger_client.api.users_api import UsersApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.accepter_data import AccepterData
from swagger_client.models.accepter_responce import AccepterResponce
from swagger_client.models.account_info import AccountInfo
from swagger_client.models.account_responce import AccountResponce
from swagger_client.models.auth_responce import AuthResponce
from swagger_client.models.cassette_data import CassetteData
from swagger_client.models.cassette_data_banknote import CassetteDataBanknote
from swagger_client.models.collection import Collection
from swagger_client.models.collection_responce import CollectionResponce
from swagger_client.models.create_operation import CreateOperation
from swagger_client.models.created_responce import CreatedResponce
from swagger_client.models.credit import Credit
from swagger_client.models.credit_responce import CreditResponce
from swagger_client.models.credit_review import CreditReview
from swagger_client.models.credit_review_responce import CreditReviewResponce
from swagger_client.models.debit import Debit
from swagger_client.models.debit_responce import DebitResponce
from swagger_client.models.debit_review import DebitReview
from swagger_client.models.debit_review_responce import DebitReviewResponce
from swagger_client.models.error400 import Error400
from swagger_client.models.error404 import Error404
from swagger_client.models.error422 import Error422
from swagger_client.models.error500 import Error500
from swagger_client.models.find_user import FindUser
from swagger_client.models.find_user_data import FindUserData
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.inline_response200_data import InlineResponse200Data
from swagger_client.models.operation_create_responce import OperationCreateResponce
from swagger_client.models.settings_data import SettingsData
from swagger_client.models.settings_data_api_config import SettingsDataAPIConfig
from swagger_client.models.settings_data_bill_acceptor_config import SettingsDataBillAcceptorConfig
from swagger_client.models.settings_data_bill_dispenser_config import SettingsDataBillDispenserConfig
from swagger_client.models.settings_data_printer_config import SettingsDataPrinterConfig
from swagger_client.models.settings_responce import SettingsResponce
from swagger_client.models.transfer_account import TransferAccount
from swagger_client.models.transfer_responce import TransferResponce
from swagger_client.models.user import User
from swagger_client.models.user_created_responce import UserCreatedResponce
