# coding: utf-8

"""
    Safemat Api

    The Safemat REST API permits applications to connect securely to the Safemat software to carry out a multitude of operations.  Authentication and token-based access control is enforced.  ### Token: <table><thead><tr><th>Name</th><th>Token type</th><th>Lifetime</th></tr></thead><tbody><tr><td>Access token</td><td><a rel=\"noopener noreferrer\" target=\"_blank\" href=\"https://jwt.io/\">JWT</a>., Bearer token</td><td>60m</td></tr></tbody></table>  ### Access token usage  API requests (where authorisation is required) must include the bearer access token in the header.  Once the access token expires it should be refreshed.   ### How to determine if the token has expired <ol> <li>The API returns a 401 error.</li> <li>Check the <code>exp</code> field in the token payloads.</li> </ol>  ### Token structure  <table><thead><tr><th>Key name</th><th>Description</th></tr></thead><tbody><tr><td>exp</td><td>Expiration date and time in UNIX format</td></tr><tr><td>uid</td><td>Token owner(Unique number of devices(terminal))</td></tr><tr><td>terminal_id</td><td>Id in base of devices(terminal`s)</td></tr><tr><td>iat</td><td>Created date and time in UNIX format</td></tr></tbody></table>    # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TransferAccount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'amount': 'str',
        'status': 'str',
        'id_bank_transaction': 'int',
        'id_system_transaction': 'int',
        'currency': 'str',
        'description': 'str'
    }

    attribute_map = {
        'amount': 'amount',
        'status': 'status',
        'id_bank_transaction': 'id_bank_transaction',
        'id_system_transaction': 'id_system_transaction',
        'currency': 'currency',
        'description': 'description'
    }

    def __init__(self, amount=None, status=None, id_bank_transaction=None, id_system_transaction=None, currency=None, description=None):  # noqa: E501
        """TransferAccount - a model defined in Swagger"""  # noqa: E501
        self._amount = None
        self._status = None
        self._id_bank_transaction = None
        self._id_system_transaction = None
        self._currency = None
        self._description = None
        self.discriminator = None
        if amount is not None:
            self.amount = amount
        if status is not None:
            self.status = status
        if id_bank_transaction is not None:
            self.id_bank_transaction = id_bank_transaction
        if id_system_transaction is not None:
            self.id_system_transaction = id_system_transaction
        if currency is not None:
            self.currency = currency
        if description is not None:
            self.description = description

    @property
    def amount(self):
        """Gets the amount of this TransferAccount.  # noqa: E501


        :return: The amount of this TransferAccount.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this TransferAccount.


        :param amount: The amount of this TransferAccount.  # noqa: E501
        :type: str
        """

        self._amount = amount

    @property
    def status(self):
        """Gets the status of this TransferAccount.  # noqa: E501


        :return: The status of this TransferAccount.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this TransferAccount.


        :param status: The status of this TransferAccount.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def id_bank_transaction(self):
        """Gets the id_bank_transaction of this TransferAccount.  # noqa: E501

        id transaction in bank system  # noqa: E501

        :return: The id_bank_transaction of this TransferAccount.  # noqa: E501
        :rtype: int
        """
        return self._id_bank_transaction

    @id_bank_transaction.setter
    def id_bank_transaction(self, id_bank_transaction):
        """Sets the id_bank_transaction of this TransferAccount.

        id transaction in bank system  # noqa: E501

        :param id_bank_transaction: The id_bank_transaction of this TransferAccount.  # noqa: E501
        :type: int
        """

        self._id_bank_transaction = id_bank_transaction

    @property
    def id_system_transaction(self):
        """Gets the id_system_transaction of this TransferAccount.  # noqa: E501


        :return: The id_system_transaction of this TransferAccount.  # noqa: E501
        :rtype: int
        """
        return self._id_system_transaction

    @id_system_transaction.setter
    def id_system_transaction(self, id_system_transaction):
        """Sets the id_system_transaction of this TransferAccount.


        :param id_system_transaction: The id_system_transaction of this TransferAccount.  # noqa: E501
        :type: int
        """

        self._id_system_transaction = id_system_transaction

    @property
    def currency(self):
        """Gets the currency of this TransferAccount.  # noqa: E501


        :return: The currency of this TransferAccount.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this TransferAccount.


        :param currency: The currency of this TransferAccount.  # noqa: E501
        :type: str
        """

        self._currency = currency

    @property
    def description(self):
        """Gets the description of this TransferAccount.  # noqa: E501


        :return: The description of this TransferAccount.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TransferAccount.


        :param description: The description of this TransferAccount.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TransferAccount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransferAccount):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
